site_name: Server Tutorial
site_url: https://sjohnsonaz.github.io/server-tutorial
repo_url: https://github.com/sjohnsonaz/server-tutorial
copyright: Copyright &copy; 2017 Sean Johnson
pages:
    - Home: index.md
    - Overview:
        - Concepts: 0-Overview/0.0-Concepts.md
    - Web Server:
        - Getting Started: 1-Web-Server/1.0-Getting-Started.md
        - Server Creation: 1-Web-Server/1.1-Server-Creation.md
    - Web Application:
        - Node.js: 2-Web-Application/2.0-Node.js.md
theme: readthedocs